branch-defaults:
  anto:
    environment: ba-express-dev
environment-defaults:
  ba-express-dev:
    branch: anto
    repository: ba-express
global:
  application_name: ba-express
  default_ec2_keyname: test
  default_platform: arn:aws:elasticbeanstalk:ap-southeast-1::platform/Node.js running
    on 64bit Amazon Linux/4.4.5
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: boxaladin
  sc: git
  workspace_type: Application
