'use strict';

module.exports = {
  up : function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('products', [{
      productName : 'Pulsa Telkomsel 100000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Pulsa Telkomsel 50000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Telkomsel 20000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 100000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 50000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 20000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 100000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Paket Data Telkomsel 50000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 20000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }], {});
  },

  down : function (queryInterface, Sequelize) {
    queryInterface.bulkDelete('products', [{
      productName : 'Pulsa Telkomsel 100000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Pulsa Telkomsel 50000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Telkomsel 20000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 100000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 50000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 20000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 100000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Paket Data Telkomsel 50000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 20000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }], {});
  },
};
