'use strict';

module.exports = {
  up : function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('products', [{
      productName : 'Pulsa Telkomsel 10.000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Pulsa Telkomsel 50.000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Telkomsel 100.000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 10.000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 50.000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 100.000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Indosat 10.000',
      categoryId : 1,
      brandId : 3,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Indosat 50.000',
      categoryId : 1,
      brandId : 3,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Indosat 100.000',
      categoryId : 1,
      brandId : 3,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Tri 10.000',
      categoryId : 1,
      brandId : 4,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Tri 50.000',
      categoryId : 1,
      brandId : 4,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Tri 100.000',
      categoryId : 1,
      brandId : 4,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },{
      productName : 'Pulsa Axis 10.000',
      categoryId : 1,
      brandId : 5,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Axis 50.000',
      categoryId : 1,
      brandId : 5,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Axis 100.000',
      categoryId : 1,
      brandId : 5,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },{
      productName : 'Pulsa SmartFren 10.000',
      categoryId : 1,
      brandId : 6,
      description : '',
      stock : 100,
      price : 10000,
      aladinPrice : 10000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Smartfren 50.000',
      categoryId : 1,
      brandId : 6,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa SmartFren 100.000',
      categoryId : 1,
      brandId : 6,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }], {});
  },

  down : function (queryInterface, Sequelize) {
    queryInterface.bulkDelete('products', [{
      productName : 'Pulsa Telkomsel 100000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Pulsa Telkomsel 50000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa Telkomsel 20000',
      categoryId : 1,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 100000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 50000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Pulsa XL 20000',
      categoryId : 1,
      brandId : 2,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 100000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 100000,
      aladinPrice : 100000,
      createdAt : new Date(),
      updatedAt : new Date(),
    },
    {
      productName : 'Paket Data Telkomsel 50000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 50000,
      aladinPrice : 50000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }, {
      productName : 'Paket Data Telkomsel 20000',
      categoryId : 2,
      brandId : 1,
      description : '',
      stock : 100,
      price : 20000,
      aladinPrice : 20000,
      createdAt : new Date(),
      updatedAt : new Date(),
    }], {});
  },
};
